- hosts: localhost
  connection: local
  remote_user: root
  sudo: yes

  vars:
  # データベースのユーザ名とパスワード設定（変更可能）
   mysql_db_user: oc_dbadmin
   mysql_db_password: owncloud
   php_timezone: Asia/Tokyo
   path_document_root: /var/www/html/owncloud

  vars_prompt:
  - name: yum_update
    prompt: "Do you accept updates ?"
    private: no
    default: Y

  tasks:
  - name: Yum update packages
    yum: name=* state=latest
    when: yum_update == "Y" 

  - name: Install SCL repository
    yum: name=centos-release-scl state=present

  - name: Install ownCloud reopsitory
    #CentOS7.x用ownCloud9レポジトリのインストール。
    get_url: url=http://download.owncloud.org/download/repositories/stable/CentOS_7/ce:stable.repo dest=/etc/yum.repos.d/
    
  - name: Install WEB services
    yum: name="{{ item }}" state=present
    with_items:
      - httpd
      - mod_ssl
      - php

  - name: Install PHP packages
  # PHP5.5をインストール。
    yum: name="{{ item }}" state=present
    with_items:
      - php55
      - php55-php
      - php55-php-gd
      - php55-php-mbstring
      - php55-php-mysqlnd
      - php55-php-ldap
      
  - name: PHP5.5 setting
  # PHPモジュールの設定
    command: mv /etc/httpd/conf.d/php.conf /etc/httpd/conf.d/php54.off
    command: mv /etc/httpd/conf.modules.d/10-php.conf /etc/httpd/conf.modules.d/10-php54.off
   
  - copy: src=/opt/rh/httpd24/root/etc/httpd/conf.d/php55-php.conf dest=/etc/httpd/conf.d/
  - copy: src=/opt/rh/httpd24/root/etc/httpd/conf.modules.d/10-php55-php.conf dest=/etc/httpd/conf.modules.d/
  - copy: src=/opt/rh/httpd24/root/etc/httpd/modules/libphp55-php5.so dest=/etc/httpd/modules/ owner=root group=root mode=655

  - name: Install MariaDB
  # MariaDBをインストール。
    yum: name="{{ item }}" state=present
    with_items:
      - mariadb-server
      - mariadb
      - mariadb-libs
      - MySQL-python
      
  - name: Start mariadb 
  # MariaDBの起動
    service: name=mariadb state=started
    
  - name: Install Memchache packages
    yum: name="{{ item }}" state=present
    with_items:
      - php-pecl-apc
      - php-pecl-memcache
      - memcached-devel

  - name: Create owncloud DataBase
  # ownCloudのデータベースを作成する。
    mysql_db:
     name=owncloud
  
  - name: Set DBUser and Password
    mysql_user:
     name={{ mysql_db_user }}
     password={{ mysql_db_password }}
     priv=owncloud.*:ALL

  - name: Install ownCloud
  # ownCloudのインストール。
    yum: name="{{ item }}" state=present
    with_items:
      - owncloud
      - owncloud-files

  - name: Make owncloud data dir
  # ownCloud用データ領域の作成
    file: dest=/home/owncloud/data owner=apache group=apache state=directory

  - name: Change php timezone
  # phpタイムゾーンの変更
    replace: >-
      dest=/etc/php.ini
      regexp="^;date\.timezone ="
      replace="date.timezone = {{ php_timezone }}"

  - name: Change php setting 
  # PHPの設定変更
  # change expose_php
    replace: >-
       dest=/etc/php.ini
       regexp="^expose_php = On"
       replace="expose_php = Off"
       
    # Change php default_charset
    replace: >-
       dest=/etc/php.ini
       regexp=";default_charset ="
       replace="default_charset ="
       
  - name: Change Apache DocumentRoot
  # Apache DocumentRootの変更。
    replace: >-
       dest='/etc/httpd/conf/httpd.conf'
       regexp='^DocumentRoot .*'
       replace='DocumentRoot "{{ path_document_root }}/"'
  - name: create self signed certificate
    shell: |
       crt_file="/etc/pki/tls/certs/{{ inventory_hostname }}.crt" &&
       key_file="/etc/pki/tls/private/{{ inventory_hostname }}.key" &&
       crt_and_key_file="/etc/pki/tls/private/{{ inventory_hostname }}.crt_and_key" &&
       subject="/C=JP/CN={{ inventory_hostname }}" &&
       openssl req -new -newkey rsa:2048 -sha1 -x509 -nodes \
        -set_serial 1 \
        -days 365 \
        -subj "$subject" \
        -out "$crt_file" \
        -keyout "$key_file" &&
       cat "$crt_file" "$key_file" >> "$crt_and_key_file" &&
       chmod 400 "$key_file" "$crt_and_key_file"
       creates="/etc/pki/tls/certs/{{ inventory_hostname }}.crt"
       
  - name: Change ssl document root
    replace: >-
       dest='/etc/httpd/conf.d/ssl.conf'
       regexp='^#DocumentRoot .*'
       replace='DocumentRoot "{{ path_document_root }}/"'

  - name: Strict-Transport-Security
    lineinfile:
       dest='/etc/httpd/conf.d/ssl.conf'
       insertafter='^#ServerName'
       line={{ item }}
    with_items:
      - 'Header always add Strict-Transport-Security "max-age=15768000; includeSubDomains; preload"'

  - name: change ssl servername
    replace: >-
       dest='/etc/httpd/conf.d/ssl.conf'
       regexp='^#ServerName .*'
       replace='ServerName "{{ inventory_hostname }}"'
       
  - name: change ssl SSLProtocol
    replace: >-
       dest='/etc/httpd/conf.d/ssl.conf'
       regexp='^SSLProtocol .*'
       replace='SSLProtocol all -SSLv2 -SSLv3'
  - name: change ssl SSLCertificateFile
  
    replace: >-
       dest='/etc/httpd/conf.d/ssl.conf'
       regexp='^SSLCertificateFile .*'
       replace='SSLCertificateFile /etc/pki/tls/certs/{{ inventory_hostname }}.crt'
       
  - name: change ssl SSLCertificateKeyFile
    replace: >-
       dest='/etc/httpd/conf.d/ssl.conf'
       regexp='^SSLCertificateKeyFile .*'
       replace='SSLCertificateKeyFile /etc/pki/tls/private/{{ inventory_hostname }}.key'
       
  - name: restart httpd
  # Apacheの再起動
    service: name=httpd state=restarted enabled=yes

  - name: restart mariadb
  # MariaDBの再起動
    service: name=mariadb state=restarted enabled=yes

  - name: start memchache
  # メモリキャッシュの有効化とサービスの起動
    service: name=memcached state=started enabled=yes
    
